forms:
  bcreg-incorp:
    path: /bcreg/incorporation
    type: issue-credential
    schema_name: registration.permitify
    page_title: BC Corporate Registry
    title: Registration
    template: bcgov.index.html
    description: >
      BC Registries and Online Services administers and supports the legal framework
      used for operating a business, not-for-profit society, cooperative association
      or financial institution in B.C. Organizations need to register, file documents
      and update records, which are kept as a matter of public record.
    explanation: Use the form below to register a BC corporation.

    js_includes:
      - src: js/bc_registries.js

    fields:
      - name: entity_type
        label: Registration Type
        type: select
        options:
          - BC Company
          - BC Unlimited Liability Company
          - Continuation In
          - Continuation In as a BC ULC
          - Extraprovincial Company
          - Limited Liability Company
          - Miscellaneous Firm
          - Sole Proprietorship
        required: true

      - name: legal_name
        label: Legal Name
        type: text
        required: true

      - name: address
        label: Mailing Address
        type: address
        required: true

    mapping:
      attributes:
        - name: corp_num
          from: helper
          source: uuid

        - name: registration_date
          from: helper
          source: now_iso

        - name: entity_status
          from: literal
          source: Active

        - name: entity_status_effective
          from: helper
          source: now_iso

        - name: entity_name_effective
          from: helper
          source: now_iso

  # bcreg-dba:
  #   path: /bcreg/dba
  #   type: issue-credential
  #   schema_name: doing_business_as.permitify
  #   page_title: BC Corporate Registry
  #   title: Doing Business As
  #   template: bcgov.index.html
  #   description: >
  #     BC Registries and Online Services administers and supports the legal framework
  #     used for operating a business, not-for-profit society, cooperative association
  #     or financial institution in B.C. Organizations need to register, file documents
  #     and update records, which are kept as a matter of public record.
  #   explanation: Use the form below to add a Doing Business As name for your business.

  #   proof_request:
  #     id: registration
  #     connection_id: bctob

  #   js_includes:
  #     - src: js/bc_registries.js

  #   hidden:
  #     - corp_num
  #     - dba_corp_num

  #   fields:
  #     - name: doing_business_as_name
  #       label: Doing Business As Name
  #       type: text
  #       required: true

  #     - name: address
  #       label: Mailing Address
  #       type: address
  #       required: true

  #   mapping:
  #     attributes:
  #       - name: dba_corp_num
  #         from: helper
  #         source: uuid
