forms:
  finance-pst:
    path: /surrey/biz
    type: issue-credential
    schema_name: biz_license.permitify
    page_title: City of Surrey
    title: Surrey
    template: city_of_surrey.index.html
    description: >
      Business Licensing
    explanation: To conduct your business in Surrey, you must have a valid business licence.

    proof_request:
      id: registration
      connection_id: bctob

    fields:
      - name: corp_num
        label: Corporation ID
        type: text
        required: true
        # disabled: true

      # - name: dba_corp_num
      #   label: Doing Business As ID
      #   type: text
      #   required: true
      #   disabled: true

      - name: legal_name
        label: Legal Name
        type: text
        required: true
        # disabled: true

      # - name: doing_business_as_name
      #   label: Doing Business As Name
      #   type: text
      #   required: true
      #   disabled: true

      - name: number_of_employees
        label: Number of Employees
        type: number
        required: true

      - name: effective_date
        label: Effective Date
        type: date
        required: true
