default:
  APPLICATION_URL_INCORP: $APPLICATION_URL/surrey/biz
  TEMPLATE_PATH: ../templates
  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080
  INDY_WALLET_SEED: ministry_surrey_dev_000000000000
