- name: incorporation.bc_registries
  version: '1.0.31'
  attributes:
    - legal_entity_id
    - corp_num
    - legal_name
    - org_type
    - addressee
    - address_line_1
    - address_line_2
    - city
    - province
    - postal_code
    - country
    - effective_date
    - end_date

- name: doing_business_as.bc_registries
  version: '1.0.31'
  attributes:
    - legal_entity_id
    - corp_num
    - legal_name
    - doing_business_as_name
    - addressee
    - address_line_1
    - address_line_2
    - city
    - province
    - postal_code
    - country
    - effective_date
    - end_date
